const level_1 = new level (
    [
        new Demon(),
        new Demon(),
        new Demon(),
        new Demon(),
        new Demon(),
        new Demon(),

        new Crow(),
        new Crow(),
        new Crow(),
        new Crow(),
        new Crow(),
        new Crow(),
        new Crow(),
        new Crow(),
        new Crow(),
        new Crow(),
        
        new Endboss()
    ],
        
    [
        new Sky('img/background/sky.png', -1344, 0),
        new Sky('img/background/sky.png', 0, 0),
        new Sky('img/background/sky.png', 1343, 0),
        new Sky('img/background/sky.png', 1344 * 2, 0),
        new Sky('img/background/sky.png', 1344 * 3, 0),
        new Sky('img/background/sky.png', 1344 * 4, 0),
        new Sky('img/background/sky.png', 1344 * 4, 0),
        new Sky('img/background/sky.png', 1344 * 5, 0),
        new Sky('img/background/sky.png', 1344 * 6, 0),
        new Sky('img/background/sky.png', 1344 * 7, 0),
        new Sky('img/background/sky.png', 1344 * 8, 0),
        new Sky('img/background/sky.png', 1344 * 9, 0),
        new Sky('img/background/sky.png', 1344 * 10, 0),
        new Sky('img/background/sky.png', 1344 * 11, 0),
        new Sky('img/background/sky.png', 1344 * 12, 0),
    ],

    [
        new BackgroundObject('img/background/graves.png', -1344, 0),
        new BackgroundObject('img/background/backTrees.png', -1344, 0),
        // new BackgroundObject('img/background/crypt.png', -1344, 0),
        new BackgroundObject('img/background/wall.png', -1344, 0),
        new BackgroundObject('img/background/ground.png', -1344, 0),
        // new BackgroundObject('img/background/tree.png', -1344, 0),
        new BackgroundObject('img/background/bones.png', -1344, 0),

        new BackgroundObject('img/background/graves.png', 0, 0),
        new BackgroundObject('img/background/backTrees.png', 0, 0),
        new BackgroundObject('img/background/crypt.png', 0, 0),
        new BackgroundObject('img/background/wall.png', 0, 0),
        new BackgroundObject('img/background/ground.png', 0, 0),
        new BackgroundObject('img/background/tree.png', 0, 0),
        new BackgroundObject('img/background/bones.png', 0, 0),

        new BackgroundObject('img/background/graves.png', 1344, 0),
        new BackgroundObject('img/background/backTrees.png', 1344, 0),
        // new BackgroundObject('img/background/crypt.png', 1344, 0),
        new BackgroundObject('img/background/wall.png', 1344, 0),
        new BackgroundObject('img/background/ground.png', 1344, 0),
        // new BackgroundObject('img/background/tree.png', 1344, 0),
        new BackgroundObject('img/background/bones.png', 1344, 0),

        new BackgroundObject('img/background/graves.png', 1344 * 2, 0),
        new BackgroundObject('img/background/backTrees.png', 1344 * 2, 0),
        new BackgroundObject('img/background/crypt.png', 1344 * 2, 0),
        new BackgroundObject('img/background/wall.png', 1344 * 2, 0),
        new BackgroundObject('img/background/ground.png', 1344 * 2, 0),
        new BackgroundObject('img/background/tree.png', 1344 * 2, 0),
        new BackgroundObject('img/background/bones.png', 1344 * 2, 0),

        new BackgroundObject('img/background/graves.png', 1344 * 3, 0),
        new BackgroundObject('img/background/backTrees.png', 1344 * 3, 0),
        // new BackgroundObject('img/background/crypt.png', 1344 * 3, 0),
        new BackgroundObject('img/background/wall.png', 1344 * 3, 0),
        new BackgroundObject('img/background/ground.png', 1344 * 3, 0),
        // new BackgroundObject('img/background/tree.png', 1344 * 3, 0),
        new BackgroundObject('img/background/bones.png', 1344 * 3, 0),

        new BackgroundObject('img/background/graves.png', 1344 * 4, 0),
        new BackgroundObject('img/background/backTrees.png', 1344 * 4, 0),
        new BackgroundObject('img/background/crypt.png', 1344 * 4, 0),
        new BackgroundObject('img/background/wall.png', 1344 * 4, 0),
        new BackgroundObject('img/background/ground.png', 1344 * 4, 0),
        new BackgroundObject('img/background/tree.png', 1344 * 4, 0),
        new BackgroundObject('img/background/bones.png', 1344 * 4, 0),
    ]
);